### ISSUE TITLE
macos chrome isn't rendering bold or italics

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/system-font-i18n-css#12]
release `1.1.0` introduces a bug on Chrome (macos) where bold and italics isn't rendering.

suspect that including `system-ui` in the font stack is at fault.

here:
https://github.com/mirai-audio/system-font-i18n-css/blob/master/system-font-i18n.css#L31

**Comment by johanbijlsma** [comment]
Hi @0xadada, I will look in to it. 

I'll let you know if I find a solution,

Johan

**Comment by johanbijlsma** [comment]
I can replicate it, but i don't see a solution. The only I found this far is replacing **system-sans-serif** to **BlinkMacSystemFont** , But I already saw this in your stylesheet.

Johan

**Comment by 0xadada** [comment]
What if you remove the 'system-ui' don't from the src list?

-------- Original Message --------
